=== kimkomorebi/xmlDoc/src/main/webapp/april1202.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT playerlist (player+)>
<!ELEMENT player 
(name,(position | location),age,height,weight,backnumber?,score?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT backnumber (#PCDATA)>
<!ELEMENT score (#PCDATA)>

=== kimkomorebi/xmlDoc/src/main/webapp/april1202.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE playerlist SYSTEM "april1202.dtd">
<playerlist>
	<player>
		<name>차범근</name>
		<location>포워드</location>
		<age>32</age>
		<height>186</height>
		<weight>89</weight>
	</player>
	<player>
		<name>손흥민</name>
		<position>포워드</position>
		<age>22</age>
		<height>188</height>
		<weight>89</weight>
		<backnumber>56</backnumber>
		<score>22</score>
	</player>
</playerlist>
