=== kimkomorebi/xmlDoc/src/main/webapp/april1401.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT booklist (book+)>
<!ELEMENT book (title, writer, price, publisher)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>

<!ATTLIST book genre (소설|과학|컴퓨터|경영) "컴퓨터" id ID #REQUIRED>

=== kimkomorebi/xmlDoc/src/main/webapp/april1401.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE booklist SYSTEM "april1401.dtd">
<booklist>
	<book id="c001" genre="컴퓨터">
		<title>XML의 기초</title>
		<writer>홍길동</writer>
		<price>10000</price>
		<publisher>길동 출판사</publisher>
	</book>
	<book id="c002" genre="컴퓨터">
		<title>XML의 기초</title>
		<writer>홍길동</writer>
		<price>10000</price>
		<publisher>길동 출판사</publisher>
	</book>
</booklist>
