=== kimkomorebi/xmlDoc/src/main/webapp/april1403.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT playerlist (positions, player+)>
	<!ELEMENT positions (position+)>
		<!ELEMENT position (#PCDATA)>
	<!ELEMENT player (name, team, age, height, weight)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT team (#PCDATA)>		
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT height (#PCDATA)>
		<!ELEMENT weight (#PCDATA)>
<!ATTLIST position id ID #REQUIRED>
<!ATTLIST player back ID #REQUIRED pos IDREF #REQUIRED>

=== kimkomorebi/xmlDoc/src/main/webapp/april1403.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE playerlist SYSTEM "april1403.dtd">
<playerlist>
	<positions>
		<position id="F">1루수</position><position id="P">투수</position>
		<position id="C">포수</position>
	</positions>
	<player back="B01" pos="C">
		<name>홍길동</name><team>삼성 라이언즈</team><age>32</age>
		<height>175</height><weight>78</weight>
	</player>
	<player back="B99" pos="P">
		<name>홍길동</name><team>두산 베어즈</team>
		<age>25</age><height>182</height><weight>86</weight>
	</player>
</playerlist>
