=== kimkomorebi/xmlDoc/src/main/webapp/april1404.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT playerlist (teams, positions, player+)>
	<!ELEMENT teams (team+)>
		<!ELEMENT team (#PCDATA)>
	<!ELEMENT positions (position+)>
		<!ELEMENT position (#PCDATA)>
	<!ELEMENT player (name, age, height, weight, goal)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT height (#PCDATA)>
		<!ELEMENT weight (#PCDATA)>
		<!ELEMENT goal (#PCDATA)>
<!ATTLIST team id ID #REQUIRED>		
<!ATTLIST position id ID #REQUIRED>
<!ATTLIST player back ID #REQUIRED 
		team IDREF #REQUIRED pos IDREF #REQUIRED>

=== kimkomorebi/xmlDoc/src/main/webapp/april1404.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE playerlist SYSTEM "april1404.dtd">
<playerlist>
	<teams>
		<team id="SF">서울FC</team>
		<team id="TT">토트넘</team>
	</teams>
	<positions>
		<position id="F">포워드</position>
		<position id="D">디펜스</position>
	</positions>
	<player back="N07" team="TT" pos="F">
		<name>손흥민</name>
		<age>29</age>
		<height>183</height>
		<weight>77</weight>
		<goal>203</goal>
	</player>
</playerlist>
